### ISSUE TITLE
影视剧

### ISSUE THREAD

**Issue by fzdwx** [fzdwx/blog-history#11]
> 记录一些影视作品的观看记录

[//]: # (https://moviedb.8610000.xyz/api/v1/queue/movie/)

### 动漫

<ClientsOnly>
  <Douban code="35604677" to="https://ddys.art/the-witch-from-mercury/"/>
  <Douban code="35417872" to="https://ddys.art/isekaiojisan/"/>
  <Douban code="35853587"/>
</ClientsOnly>

### 动漫
<ClientsOnly>
  <Douban code="35351365"/>
  <Douban code="35256195" to="https://ddys.art/chainsaw-man" />
  <Douban code="35679830" to="https://www.bilibili.com/bangumi/play/ss39696" />
  <Douban code="35366293" to="https://ddys.art/bocchi-the-rock/"/>
</ClientsOnly>

### 电影

<ClientsOnly>
  <Douban code="2124724" />
  <Douban code="1304624" to="https://www.bilibili.com/bangumi/play/ss32937" />
  <Douban code="1303173" />
  <Douban code="1291550" />
  <Douban code="27060077" />
  <Douban code="30270746" />
  <Douban code="30128916" />
  <Douban code="30323380" />
</ClientsOnly>

### 电视剧

<Douban code="30198955" to="https://ddys.art/the-peripheral/" />
<Douban code="30291070" to="https://ddys.art/reborn-rich/" />
<Douban code="35314632" to="https://ddys.art/the-glory-2022" />
<Douban code="35465232" />

**Comment by fzdwx** [comment]
local wezterm = require("wezterm")
local act = wezterm.action

local keys = {
        -- { key = "=", mods = "CTRL", action = wezterm.action.DecreaseFontSize },
        -- { key = "=", mods = "CTRL|SHIFT", action = wezterm.action.IncreaseFontSize },
        -- pane
        -- 在一个tab内切分的子pane中移动
        { key = "LeftArrow", mods = "ALT", action = wezterm.action({ ActivatePaneDirection = "Left" }) },
        { key = "RightArrow", mods = "ALT", action = wezterm.action({ ActivatePaneDirection = "Right" }) },
        { key = "UpArrow", mods = "ALT", action = wezterm.action({ ActivatePaneDirection = "Up" }) },
        { key = "DownArrow", mods = "ALT", action = wezterm.action({ ActivatePaneDirection = "Down" }) },

        {
                key = "LeftArrow",
                mods = "CTRL",
                action = act.AdjustPaneSize({ "Left", 5 }),
	},
	{
		key = "DownArrow",
		mods = "CTRL",
		action = act.AdjustPaneSize({ "Down", 5 }),
	},
	{ key = "UpArrow", mods = "CTRL", action = act.AdjustPaneSize({ "Up", 5 }) },
	{
		key = "RightArrow",
		mods = "CTRL",
		action = act.AdjustPaneSize({ "Right", 5 }),
	},
	-- 向下分割 CTRL + -
	{ key = "-", mods = "ALT", action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }) },
	-- 向右分割 CTRL + \
	{ key = "\\", mods = "ALT", action = wezterm.action({ SplitHorizontal = { domain = "CurrentPaneDomain" } }) },

        -- tab
        -- 新建一个会话
        { key = "C", mods = "CTRL", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) },
        -- 关闭tab
        { key = "d", mods = "ALT", action = wezterm.action.CloseCurrentTab({ confirm = true }) },
        -- 先前向后移动大的tab
        { key = "1", mods = "ALT", action = wezterm.action({ ActivateTab = 0 }) },
        { key = "2", mods = "ALT", action = wezterm.action({ ActivateTab = 1 }) },
        { key = "3", mods = "ALT", action = wezterm.action({ ActivateTab = 2 }) },
        { key = "4", mods = "ALT", action = wezterm.action({ ActivateTab = 3 }) },
        { key = "5", mods = "ALT", action = wezterm.action({ ActivateTab = 4 }) },
        { key = "6", mods = "ALT", action = wezterm.action({ ActivateTab = 5 }) },
        { key = "7", mods = "ALT", action = wezterm.action({ ActivateTab = 6 }) },
        { key = "8", mods = "ALT", action = wezterm.action({ ActivateTab = 7 }) },
        { key = "9", mods = "ALT", action = wezterm.action({ ActivateTab = -1 }) },
}

local mouse_bindings = {
        -- 右键粘贴
        {
                event = { Down = { streak = 1, button = "Right" } },
                mods = "NONE",
                action = wezterm.action({ PasteFrom = "Clipboard" }),
        },
        -- 选中复制
        {
                event = { Up = { streak = 1, button = "Left" } },
                mods = "NONE",
                action = wezterm.action.CompleteSelection("Clipboard"),
        },
}

wezterm.on("update-right-status", function(window, pane)
        local date = "  " .. wezterm.strftime("%a %b %-d %H:%M  ")

        window:set_right_status(wezterm.format({
                { Attribute = { Underline = "Single" } },
                { Attribute = { Italic = true } },
                { Foreground = { Color = "Cyan" } },
                { Text = date },
        }))
end)

-- A helper function for fallback fonts
wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
        if tab.is_active then
                return {
                        { Foreground = { Color = "Colour231" } },
                        { Background = { Color = "#24283B" } },
                        { Attribute = { Italic = true } },
                        { Text = " ﲵ : " .. tab.active_pane.title .. " " },
                }
        end
        return tab.actvie_pane.id .. tab.active_pane.title
end)

return {
        -- color_scheme = "Catppuccin Frappe",
        color_scheme = "Dracula+",
        --color_scheme = "Aura (Gogh)",
        colors = {
                selection_bg = "#7CCBFA",
        },
        --color_scheme = "tokyonight",
        font_size = 12.0,
        window_background_opacity = 0.7,
        -- Smart tab bar [distraction-free mode]
        hide_tab_bar_if_only_one_tab = true,
        mouse_bindings = mouse_bindings,
        keys = keys,
        use_ime = true,
        window_padding = {
                bottom = 0,
        },
        -- tab_bar_at_bottom = true,
        inactive_pane_hsb = {
                hue = 1.0,
                saturation = 1.0,
                brightness = 1.0,
        },
}

**Comment by fzdwx** [comment]
![image](https://github.com/fzdwx/blog-history/assets/65269574/2b59ba05-91d2-4ea0-b3ce-b12ffc0d551d)

**Comment by bsoprojects** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by dwcooper** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Magic-Fy, @Kino-Zh, @FlyingShuriken, @Qianhongrui, @wmhqnyh, @onthebigtree, @Tenlercy, @soseuqinchuan, @nacey5, @gorodamen, @Ferict, @LHY-sudo, @ygnmax, @Nomeleel, @BitoLido, @nikolahu, @SwartzMss, @1405874089, @AnZiXi, @jim1010
